[env:esp32dev]
platform = espressif32@6.5.0 
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main2.cpp> +<secrets.h>
lib_deps =
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit SHT4x Library @ ^1.0.4
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO

[env:esp32c3]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_c3.cpp> +<secrets.h>
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit SHT4x Library @ ^1.0.4
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO

[env:esp32c3_aht]
platform = espressif32@6.5.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_aht.cpp> +<secrets.h>
build_flags = 
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit AHTX0 @ ^2.0.5
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO

[env:esp32s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_c3.cpp> +<secrets.h>
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_flags = 
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit SHT4x Library @ ^1.0.4
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO

[env:esp32s3_aht]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_aht.cpp> +<secrets.h>
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_flags = 
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit MPU6050 @ ^2.2.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit AHTX0 @ ^2.0.5
  claws/BH1750 @ ^1.3.0
  mikalhart/TinyGPSPlus @ ^1.0.3
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  adafruit/Adafruit BusIO
